<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <Product>S1Utility</Product>
        <AssemblyTitle>S-1 Utility</AssemblyTitle>
        <Version>0.1.0</Version>
        <Authors>denzlobin</Authors>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="InitPatch.prm" LogicalName="InitPatch.prm" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\S1Utility.Core\S1Utility.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.1" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.1" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="managed-midi" Version="1.10.1" />
        <PackageReference Include="Melanchall.DryWetMidi" Version="8.0.3" />
    </ItemGroup>
</Project>
